apiVersion: v1
kind: ConfigMap
metadata:
  name: smokeping-config
  namespace: smokeping
data:
  config: |
    # Main smokeping config
    # See https://oss.oetiker.ch/smokeping/doc/smokeping_config.en.html
    
    *** General ***
    owner    = HomeLab
    contact  = admin@xs4some.nl
    mailhost = localhost
    charset  = utf-8
    imgcache = /data/img
    imgurl   = /smokeping/img
    datadir  = /data/rrd
    piddir   = /data/var
    cgiurl   = /smokeping/cgi
    
    *** Alerts ***
    # No alerts by default
    
    *** Database ***
    step     = 60
    pings    = 20
    
    *** Presentation ***
    template = /usr/share/smokeping/examples/basepage.html
    charset  = utf-8
    
    *** Probes ***
    + FPing
    binary = /usr/sbin/fping
    
    *** Targets ***
    probe = FPing
    
    @include /config/Targets
  Targets: |
    *** Targets ***
    probe = FPing
    menu = Top
    title = Network Latency Grapher
    remark = Welcome to SmokePing.
    
    + Local
    menu = Local
    title = Local Network (ICMP)
    
    ++ LocalMachine
    menu = Local Machine
    title = This host
    host = localhost
    
    + DNS
    menu = DNS latency
    title = DNS latency (ICMP)
    
    ++ Cloudflare
    title = Cloudflare
    host = 1.1.1.1
    
    ++ Quad9
    title = Quad9 (EU)
    host = 9.9.9.9
    
    ++ Google
    title = Google (EU)
    host = 8.8.8.8
    
    ++ ControlD
    title = Control D (NL)
    host = 76.76.2.2
    
    + ISP
    menu = ISP & CDN
    title = ISP & CDN (ICMP)
    
    ++ KPN
    title = KPN Netherlands
    host = dns.kpn.com
    
    ++ CloudflareAMS
    title = Cloudflare Amsterdam
    host = ams.cloudflare.com
    
    ++ AWSEurope
    title = AWS eu-west-1
    host = ec2.eu-west-1.amazonaws.com
    
    + Services
    menu = EU Services
    title = European Services (ICMP)
    
    ++ Tweakers
    title = Tweakers.net
    host = tweakers.net
    
    ++ NOS
    title = NOS.nl
    host = nos.nl
    
    ++ Github
    title = GitHub
    host = github.com
    
    ++ DigitalOcean
    title = DigitalOcean AMS
    host = ams3.digitalocean.com
