apiVersion: v1
kind: Service
metadata:
  name: plex-ingress
  namespace: plex
spec:
  ports:
  - port: 32400
    targetPort: 32400
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: plex-ingress
  namespace: plex
subsets:
- addresses:
  - ip: 172.16.0.8
  ports:
  - port: 32400
    protocol: TCP
    name: http
