apiVersion: v1
kind: Service
metadata:
  name: coredns-kids-external
  namespace: dns-system
spec:
  type: NodePort
  selector:
    app: coredns-kids
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
    nodePort: 30053
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
    nodePort: 30053
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-standard-external
  namespace: dns-system
spec:
  type: NodePort
  selector:
    app: coredns-standard
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
    nodePort: 30153
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
    nodePort: 30153
