apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ip-whitelist
  namespace: syncthing
spec:
  ipWhiteList:
    sourceRange:
      - 172.16.0.0/22
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: syncthing
  namespace: syncthing
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`syncthing.xs4some.nl`)
      middlewares:
        - name: ip-whitelist
      services:
        - name: syncthing
          port: 8384
  tls:
    certResolver: letsencrypt
