# Exposing Home Assistant running on hass.xs4some.local:8123

---
# Service pointing to Home Assistant
apiVersion: v1
kind: Service
metadata:
  name: hass-app
  namespace: default
spec:
  ports:
  - port: 8123
---
apiVersion: v1
kind: Endpoints
metadata:
  name: hass-app
  namespace: default
subsets:
- addresses:
  - ip: 172.16.0.117  # Home Assistant IP
  ports:
  - port: 8123
---
# Ingress to expose with SSL
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hass-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  rules:
  - host: ha.xs4some.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hass-app
            port:
              number: 8123
  tls:
  - hosts:
    - ha.xs4some.nl
