apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: switch
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`switch.xs4some.nl`)
      middlewares:
        - name: ip-whitelist
      services:
        - name: switch-external
          port: 9080
  tls:
    certResolver: letsencrypt
---
apiVersion: v1
kind: Service
metadata:
  name: switch-external
  namespace: traefik
spec:
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: switch-external
  namespace: traefik
subsets:
  - addresses:
      - ip: 172.16.0.1
    ports:
      - port: 9080
        protocol: TCP
